### ISSUE TITLE
Error: libsasl2.so.3: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by HTiswear** [cloudfoundry/nodejs-buildpack#156]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
cf version 6.23.1+a70deb3.2017-01-13

What version of the buildpack you are using?
 Nodejs Buildpack version 1.6.25

If you were attempting to accomplish a task, what was it you were attempting to do?
Push an app containing node-rdkafka dependency to PCF.

What did you expect to happen?
Build would complete. 

What was the actual behavior?
Build fails due to this error: `Error: libsasl2.so.3: cannot open shared object file: No such file or directory`

Please confirm where necessary:
* [X ] I have included a log output
* [ X] My log includes an error message
* [ ] I have included steps for reproduction

Log message:

` [ERR] module.js:604
 [ERR] return process.dlopen(module, path._makeLong(filename));
 [ERR] ^
 [ERR] Error: libsasl2.so.3: cannot open shared object file: No such file or directory
 [ERR] at Error (native)
 [ERR] at Object.Module._extensions..node (module.js:604:18)
 [ERR] at Module.load (module.js:494:32)
 [ERR] at tryModuleLoad (module.js:453:12)
 [ERR] at Function.Module._load (module.js:445:3)
 [ERR] at Module.require (module.js:504:17)
 [ERR] at require (internal/module.js:20:19)
 [ERR] at Object.<anonymous> (/home/vcap/deps/0/node_modules/node-rdkafka/librdkafka.js:11:13)
 [ERR] at Module._compile (module.js:577:32)
 [ERR] at Object.Module._extensions..js (module.js:586:10)
 [ERR] at Object.<anonymous> (/home/vcap/deps/0/node_modules/node-rdkafka/lib/client.js:14:13)
 [ERR] npm ERR! Linux 4.4.0-128-generic
 [ERR] npm ERR! argv "/home/vcap/deps/0/node/bin/node" "/home/vcap/deps/0/bin/npm" "start"
 [ERR] npm ERR! node v6.14.2
 [ERR] npm ERR! npm v3.10.10`

**Comment by sclevine** [comment]
Could you provide a sample app that we can use to debug this?

**Comment by HTiswear** [comment]
I can't post my app because it uses proprietary code, but this is the "offending" app that we're using that should throw the same error: https://github.com/Blizzard/node-rdkafka

**Comment by tylerphelan** [comment]
@HTiswear we pushed an app that pulled in the node-rdkafka module and it deployed successfully and the logs showed:

```
checking for libsasl2 (by pkg-config)... ok
checking for libsasl2 (by compile)... ok (cached)
```

Are you using the cflinuxfs2 stack? It has libsasl2 so I would expect this to work https://github.com/cloudfoundry/cflinuxfs2/blob/1.235.0/cflinuxfs2/cflinuxfs2_receipt#L385
