### ISSUE TITLE
Node application failing with Error: spawn ENOENT

### ISSUE THREAD

**Issue by antoni-g** [cloudfoundry/nodejs-buildpack#219]
**What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?**

cf version 6.46.1+4934877ec.2019-08-23

**What version of the buildpack you are using?**

Current version

**If you were attempting to accomplish a task, what was it you were attempting to do?**

Deploying application & starting

**What did you expect to happen?**

Same as on my local, application start and listening on requisite port.
The library I am using (https://github.com/mock-server/mockserver-node)
Calls a .jar file on startup.
I suspect I am getting this error because java is not installed on the CF instance.

<pre>
16:00:26.913: [APP/PROC/WEB.0] Running 'java -Dfile.encoding=UTF-8 -jar node_modules/mockserver-node/mockserver-netty-5.9.0-jar-with-dependencies.jar -serverPort 8080 -logLevel DEBUG'
16:00:26.913: [APP/PROC/WEB.0] spawn called
16:00:26.917: [APP/PROC/WEB.0] [Arguments] {
16:00:26.917: [APP/PROC/WEB.0]   '0': 'java',
16:00:26.917: [APP/PROC/WEB.0]   '1':
16:00:26.917: [APP/PROC/WEB.0]    [ '-Dfile.encoding=UTF-8',
16:00:26.917: [APP/PROC/WEB.0]      '-jar',
16:00:26.917: [APP/PROC/WEB.0]      [ 'node_modules/mockserver-node/mockserver-netty-5.9.0-jar-with-dependencies.jar' ],
16:00:26.917: [APP/PROC/WEB.0]      '-serverPort',
16:00:26.917: [APP/PROC/WEB.0]      '8080',
16:00:26.917: [APP/PROC/WEB.0]      '-logLevel',
16:00:26.917: [APP/PROC/WEB.0]      'DEBUG' ],
16:00:26.917: [APP/PROC/WEB.0]   '2': { stdio: [ 'ignore', [Socket], [Socket] ] } }
16:00:26.931: [APP/PROC/WEB.0] Using port '8080' to stop MockServer and MockServer Proxy
16:00:26.951: [APP/PROC/WEB.0] Error: spawn java ENOENT
16:00:26.951: [APP/PROC/WEB.0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
16:00:26.951: [APP/PROC/WEB.0]     at onErrorNT (internal/child_process.js:415:16)
16:00:26.951: [APP/PROC/WEB.0]     at process._tickCallback (internal/process/next_tick.js:63:19)
16:00:26.951: [APP/PROC/WEB.0]     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
16:00:26.951: [APP/PROC/WEB.0]     at startup (internal/bootstrap/node.js:283:19)
16:00:26.951: [APP/PROC/WEB.0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)

 </pre>

**What was the actual behavior?**

Failure to start, application ENOENT

**Can you provide a sample app?**

Unfortunately not, but I am using this library: 

https://github.com/mock-server/mockserver-node

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by ryanmoran** [comment]
@antoni-g can you be specific about what version of the buildpack you are using? It would also be helpful if you could include the entire log output so that we can see what happened before the error.

**Comment by antoni-g** [comment]
sure thing, I get this output not specifying a buildpack and allowing it to autodetect node (which I assume defaults to the latest version). I had exactly the same results explictly defining the latest version of this node buildpack, as well as defining node as the primary buildpack along with the latest version of the java buildpack.

Please note the "which java" error was me checking if there was a version of java on the container by outputting it to the logs and does not cause the app to crash overall

I also got the following response on this issue from the creator of the original library I am using:
https://github.com/mock-server/mockserver/issues/745#issuecomment-600517504

`09:52:02.414: [API.0] Updated app with guid 7a926901-1864-4b3a-baa9-664f9bff5a46 ({"state"=>"STARTED"})
09:52:02.645: [CELL.0] Cell b8faff0c-bd6f-4809-8a7f-86c1fa7cf32b creating container for instance db1eb52c-c67f-4e2d-41f8-c6e9
09:52:02.967: [CELL.0] Cell b8faff0c-bd6f-4809-8a7f-86c1fa7cf32b successfully created container for instance db1eb52c-c67f-4e2d-41f8-c6e9
09:52:05.453: [CELL.0] Starting health monitoring of container
09:52:06.131: [APP/PROC/WEB.0] HERE
09:52:06.132: [APP/PROC/WEB.0] HERE
09:52:06.132: [APP/PROC/WEB.0] HERE
09:52:06.132: [APP/PROC/WEB.0] HERE
09:52:06.132: [APP/PROC/WEB.0] HERE
09:52:06.133: [APP/PROC/WEB.0] HERE
09:52:06.133: [APP/PROC/WEB.0] HERE
09:52:06.133: [APP/PROC/WEB.0] HERE
09:52:06.133: [APP/PROC/WEB.0] /home/vcap/deps/0/bin:/usr/local/bin:/usr/bin:/bin:/home/vcap/app/bin:/home/vcap/app/node_modules/.bin
09:52:06.133: [APP/PROC/WEB.0] 8080
09:52:06.133: [APP/PROC/WEB.0] HERE
09:52:06.133: [APP/PROC/WEB.0] HERE
09:52:06.144: [APP/PROC/WEB.0] HERE
09:52:06.144: [APP/PROC/WEB.0] HERE
09:52:06.144: [APP/PROC/WEB.0] HERE
09:52:06.144: [APP/PROC/WEB.0] HERE
09:52:06.144: [APP/PROC/WEB.0] HERE
09:52:06.144: [APP/PROC/WEB.0] HERE
09:52:06.601: [APP/PROC/WEB.0] Running 'java -Dfile.encoding=UTF-8 -jar node_modules/mockserver-node/mockserver-netty-5.9.0-jar-with-dependencies.jar -serverPort 8080 -logLevel DEBUG'
09:52:06.601: [APP/PROC/WEB.0] spawn called
09:52:06.605: [APP/PROC/WEB.0] [Arguments] {
09:52:06.605: [APP/PROC/WEB.0]   '0': 'java',
09:52:06.605: [APP/PROC/WEB.0]   '1':
09:52:06.605: [APP/PROC/WEB.0]    [ '-Dfile.encoding=UTF-8',
09:52:06.605: [APP/PROC/WEB.0]      '-jar',
09:52:06.605: [APP/PROC/WEB.0]      [ 'node_modules/mockserver-node/mockserver-netty-5.9.0-jar-with-dependencies.jar' ],
09:52:06.605: [APP/PROC/WEB.0]      '-serverPort',
09:52:06.605: [APP/PROC/WEB.0]      '8080',
09:52:06.605: [APP/PROC/WEB.0]      '-logLevel',
09:52:06.605: [APP/PROC/WEB.0]      'DEBUG' ],
09:52:06.605: [APP/PROC/WEB.0]   '2': { stdio: [ 'ignore', [Socket], [Socket] ] } }
09:52:06.615: [APP/PROC/WEB.0] Using port '8080' to stop MockServer and MockServer Proxy
09:52:06.620: [APP/PROC/WEB.0] error: Command failed: which java
09:52:06.625: [APP/PROC/WEB.0] Error: spawn java ENOENT
09:52:06.625: [APP/PROC/WEB.0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
09:52:06.625: [APP/PROC/WEB.0]     at onErrorNT (internal/child_process.js:415:16)
09:52:06.625: [APP/PROC/WEB.0]     at process._tickCallback (internal/process/next_tick.js:63:19)
09:52:06.625: [APP/PROC/WEB.0]     at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
09:52:06.625: [APP/PROC/WEB.0]     at startup (internal/bootstrap/node.js:283:19)
09:52:06.625: [APP/PROC/WEB.0]     at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
09:52:06.506: [APP/PROC/WEB.0] Skipping {
09:52:06.506: [APP/PROC/WEB.0]   "host": "oss.sonatype.org",
09:52:06.506: [APP/PROC/WEB.0]   "path": "/content/repositories/releases/org/mock-server/mockserver-netty/5.9.0/mockserver-netty-5.9.0-jar-with-dependencies.jar",
09:52:06.506: [APP/PROC/WEB.0]   "port": 443
09:52:06.506: [APP/PROC/WEB.0] } as file already downloaded
09:52:06.724: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 110
09:52:06.825: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 109
09:52:06.926: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 108
09:52:07.128: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 106
09:52:07.027: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 107
09:52:07.229: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 105
09:52:07.330: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 104
09:52:07.431: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 103
09:52:07.531: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 102
09:52:07.632: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 101
09:52:07.734: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 100
09:52:07.835: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 99
09:52:08.138: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 96
09:52:07.936: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 98
09:52:08.239: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 95
09:52:08.037: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 97
09:52:08.341: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 94
09:52:08.442: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 93
09:52:08.543: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 92
09:52:08.644: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 91
09:52:08.746: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 90
09:52:08.847: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 89
09:52:08.948: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 88
09:52:09.049: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 87
09:52:09.150: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 86
09:52:09.251: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 85
09:52:09.453: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 83
09:52:09.352: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 84
09:52:09.554: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 82
09:52:09.655: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 81
09:52:09.756: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 80
09:52:09.858: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 79
09:52:10.060: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 77
09:52:09.959: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 78
09:52:10.363: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 74
09:52:10.464: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 73
09:52:10.565: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 72
09:52:10.666: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 71
09:52:10.767: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 70
09:52:10.868: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 69
09:52:10.969: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 68
09:52:11.070: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 67
09:52:11.171: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 66
09:52:11.272: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 65
09:52:11.373: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 64
09:52:11.474: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 63
09:52:11.575: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 62
09:52:11.677: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 61
09:52:11.778: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 60
09:52:11.880: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 59
09:52:11.982: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 58
09:52:12.083: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 57
09:52:12.184: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 56
09:52:12.285: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 55
09:52:12.489: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 53
09:52:12.388: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 54
09:52:12.591: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 52
09:52:12.793: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 50
09:52:12.692: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 51
09:52:12.894: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 49
09:52:12.998: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 48
09:52:13.200: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 46
09:52:13.099: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 47
09:52:13.301: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 45
09:52:13.403: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 44
09:52:13.504: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 43
09:52:13.605: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 42
09:52:13.807: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 40
09:52:13.706: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 41
09:52:13.908: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 39
09:52:14.009: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 38
09:52:14.111: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 37
09:52:14.212: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 36
09:52:14.314: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 35
09:52:14.415: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 34
09:52:14.516: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 33
09:52:14.616: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 32
09:52:14.820: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 30
09:52:14.718: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 31
09:52:14.923: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 29
09:52:15.025: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 28
09:52:15.328: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 25
09:52:15.531: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 23
09:52:15.429: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 24
09:52:15.636: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 22
09:52:15.737: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 21
09:52:15.838: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 20
09:52:15.939: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 19
09:52:16.040: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 18
09:52:16.144: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 17
09:52:16.454: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 14
09:52:16.249: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 16
09:52:16.352: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 15
09:52:16.555: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 13
09:52:16.660: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 12
09:52:16.862: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 10
09:52:16.761: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 11
09:52:17.065: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 8
09:52:16.963: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 9
09:52:17.170: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 7
09:52:17.272: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 6
09:52:17.474: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 4
09:52:17.373: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 5
09:52:17.781: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 1
09:52:17.575: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 3
09:52:17.680: [APP/PROC/WEB.0] waiting for MockServer to start retries remaining: 2
09:52:17.782: [APP/PROC/WEB.0] MockServer failed to start
09:52:17.782: [APP/PROC/WEB.0] {
09:52:17.782: [APP/PROC/WEB.0]   "errno": "ECONNREFUSED",
09:52:17.782: [APP/PROC/WEB.0]   "code": "ECONNREFUSED",
09:52:17.782: [APP/PROC/WEB.0]   "syscall": "connect",
09:52:17.782: [APP/PROC/WEB.0]   "address": "127.0.0.1",
09:52:17.782: [APP/PROC/WEB.0]   "port": 8080
09:52:17.782: [APP/PROC/WEB.0] }
09:52:17.790: [APP/PROC/WEB.0] Exit status 0
09:52:17.793: [CELL/SSHD.0] Exit status 0
09:52:18.329: [API.0] Process has crashed with type: "web"
09:52:18.335: [API.0] App instance exited with guid 7a926901-1864-4b3a-baa9-664f9bff5a46 payload: {"instance"=>"db1eb52c-c67f-4e2d-41f8-c6e9", "index"=>0, "cell_id"=>"b8faff0c-bd6f-4809-8a7f-86c1fa7cf32b", "reason"=>"CRASHED", "exit_description"=>"Codependent step exited", "crash_count"=>1, "crash_timestamp"=>1587390738283034821, "version"=>"e85de780-c3cf-4e85-a49b-d4583ce6a1b2"}
09:52:18.333: [CELL.0] Cell b8faff0c-bd6f-4809-8a7f-86c1fa7cf32b stopping instance db1eb52c-c67f-4e2d-41f8-c6e9
09:52:18.333: [CELL.0] Cell b8faff0c-bd6f-4809-8a7f-86c1fa7cf32b destroying container for instance db1eb52c-c67f-4e2d-41f8-c6e9
09:52:18.994: [CELL.0] Cell b8faff0c-bd6f-4809-8a7f-86c1fa7cf32b successfully destroyed container for instance db1eb52c-c67f-4e2d-41f8-c6e9`

**Comment by ryanmoran** [comment]
Sorry for the long delay in responding, but this sounds like you need to use the ["multi-buildpack" features](https://docs.cloudfoundry.org/buildpacks/use-multiple-buildpacks.html) of Cloud Foundry. In this case, you will specify that you want to deploy with both Java and Node.

**Comment by antoni-g** [comment]
@ryanmoran Hi Ryan, I actually was pushing this with both the node and java buildpacks together. I saw that from Node.js I still could not spawn or even run "which java"

**Comment by thitch97** [comment]
Hi @antoni-g, could you provide the `cf push` command you ran and the immediate resulting output from that command?

**Comment by ForestEckhardt** [comment]
Closing due to inactivity. Please feel free to reopen if you have an update or more to discuss.
