### ISSUE TITLE
Error: connect ECONNREFUSED

### ISSUE THREAD

**Issue by yookore** [cloudfoundry/nodejs-buildpack#43]
hi,

We suddenly started seeing below errors in all our NodeJS apps:
```
2016-01-14T23:35:32.14+0200 [App/0]      ERR events.js:85
2016-01-14T23:35:32.14+0200 [App/0]      ERR       throw er; // Unhandled 'error' event
2016-01-14T23:35:32.14+0200 [App/0]      ERR             ^
2016-01-14T23:35:32.14+0200 [App/0]      ERR Error: connect ECONNREFUSED
2016-01-14T23:35:32.14+0200 [App/0]      ERR     at exports._errnoException (util.js:746:11)
2016-01-14T23:35:32.14+0200 [App/0]      ERR     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1010:19)
```
No firewall setup on our CF network and I'm using v1.4.2 and v1.5.0 versions of the buildpack.

Any ideas please?

**Comment by jtarchie** [comment]
@yookore, could you provide us with the entire `cf push` logging? It helps to have context where this appeared in the buildpack staging process.

Are you vendoring `node_modules` on your `cf push`?

**Comment by Dannyzen** [comment]
@yookore Do you still need assistance or can we close this issue out?
