### ISSUE TITLE
Error injecting Sealights: failed to read start script from package.json with 1.7.68

### ISSUE THREAD

**Issue by trigunam** [cloudfoundry/nodejs-buildpack#439]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?
NA

What version of the buildpack you are using?
1.7.68

If you were attempting to accomplish a task, what was it you were attempting to do?
cf push

What did you expect to happen?
pushing binaries using manifest succeed.

What was the actual behavior?
Thrown error with `Error injecting Sealights: failed to read start script from package.json`

Can you provide a sample app?
will try to provide by tomorrow. Looks like 1.7.68 has broken a default package.json of a node.js project.

This does seem to work fine for 1.7.67.

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [x] I have included steps for reproduction

**Comment by thelangley** [comment]
we've started to see hideous explody death too since 1.7.68

```
   2022-04-07T16:51:41.65+0100 [STG/0] OUT        Inside Sealights hook
   2022-04-07T16:51:41.65+0100 [STG/0] OUT        Integrating sealights into package.json
   2022-04-07T16:51:41.66+0100 [STG/0] ERR panic: interface conversion: interface {} is nil, not map[string]interface {}
   2022-04-07T16:51:41.66+0100 [STG/0] ERR goroutine 1 [running]:
   2022-04-07T16:51:41.66+0100 [STG/0] ERR github.com/cloudfoundry/nodejs-buildpack/src/nodejs/hooks.(*SealightsHook).SetApplicationStartInPackageJson(0xc0000b60f0, 0xc0000aa780, 0x6, 0x77a2b2)
   2022-04-07T16:51:41.66+0100 [STG/0] ERR 	/tmp/buildpack-packager157580096/src/nodejs/hooks/sealights.go:129 +0x4c5
   2022-04-07T16:51:41.66+0100 [STG/0] ERR github.com/cloudfoundry/nodejs-buildpack/src/nodejs/hooks.(*SealightsHook).injectSealights(0xc0000b60f0, 0xc0000aa780, 0x6, 0x771b51)
   2022-04-07T16:51:41.66+0100 [STG/0] ERR 	/tmp/buildpack-packager157580096/src/nodejs/hooks/sealights.go:293 +0x1a5
   2022-04-07T16:51:41.66+0100 [STG/0] ERR github.com/cloudfoundry/nodejs-buildpack/src/nodejs/hooks.(*SealightsHook).AfterCompile(0xc0000b60f0, 0xc0000aa780, 0x0, 0x0)
   2022-04-07T16:51:41.66+0100 [STG/0] ERR 	/tmp/buildpack-packager157580096/src/nodejs/hooks/sealights.go:66 +0x85
   2022-04-07T16:51:41.66+0100 [STG/0] ERR github.com/cloudfoundry/libbuildpack.RunAfterCompile(0xc0000aa780, 0x0, 0x0)
   2022-04-07T16:51:41.66+0100 [STG/0] ERR 	/tmp/buildpack-packager157580096/vendor/github.com/cloudfoundry/libbuildpack/hooks.go:37 +0x71
   2022-04-07T16:51:41.66+0100 [STG/0] ERR main.main()
   2022-04-07T16:51:41.66+0100 [STG/0] ERR 	/tmp/buildpack-packager157580096/src/nodejs/finalize/cli/main.go:61 +0x3d8
   2022-04-07T16:51:41.77+0100 [STG/0] ERR Failed to compile droplet: Failed to run finalize script: exit status 2
```

**Comment by brayanhenao** [comment]
Hi @trigunam @thelangley,

Thanks for reporting the issue. We are investigating the problem, we will keep you informed.

**Comment by brayanhenao** [comment]
> Hi @trigunam @thelangley,
> 
> Thanks for reporting the issue. We are investigating the problem, we will keep you informed.

@trigunam @thelangley We just release a new version of NodeJS Buildpack ([`v1.7.69`](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.7.69)) with the corresponding fixes.

**Comment by SimonSealights** [comment]
@trigunam thanks for the bug report
How did you reproduce this scenario? Could you please provide more details about how you did it?

Also did you got to provide a sample app like you mentioned?
_will try to provide by tomorrow. Looks like 1.7.68 has broken a default package.json of a node.js project._

**Comment by trigunam** [comment]
I could not attach package.json here but posted the same in slack: https://cloudfoundry.slack.com/archives/C031GBTL8JZ/p1650263330421299?thread_ts=1650009009.362089&cid=C031GBTL8JZ

note that we are using node engine 16 and other packages relevant to our project.

All we did was used a build pack URL that points to the latest during deployment and it worked for 1.7.67 and failed for 1.7.68., but later again worked for 1.7.69 So not really sure what change kept this oscillation.
