### ISSUE TITLE
My nodejs application can't work if the version nodejs buildpack >= v1.5.9

### ISSUE THREAD

**Issue by samdai** [cloudfoundry/nodejs-buildpack#59]
Hello,
I have a nodejs application, it can be deployed and started in CF if  the version nodejs buildpack <v 1.5.9,  the version of node and npm in package.json of my nodejs application is as below:

```
, "engines" : {
    "node" : "~0.12.7",
    "npm" : "~2.11.3"
   }
```

The version of CF release is  v235, Diego version is v0.1467.0.

When I deployed my nodejs application to nodejs v1.5.9, there is the following error, do I need change something?
```
Downloading nodejs_buildpack...

Downloaded nodejs_buildpack (60.7M)

Creating container

Successfully created container

Downloading app package...

Downloaded app package (4.8M)

Staging...

-------> Buildpack version 1.5.11

-----> Creating runtime environment

       

       NPM_CONFIG_LOGLEVEL=error

       NPM_CONFIG_PRODUCTION=true

       NODE_ENV=production

       NODE_MODULES_CACHE=true

-----> Installing binaries

       engines.node (package.json):  ~0.12.7

       engines.npm (package.json):   ~2.11.3

       

       Downloading and installing node 0.12.13...

       Downloaded [file:///tmp/buildpacks/d9e57be809c47eef0c67cf7e2b84bbbe/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_node_node-0.12.13-linux-x64.tgz]

       Resolving npm version ~2.11.3 via semver.io...

       Downloading and installing npm 2.11.3 (replacing version 2.15.0)...

-----> Restoring cache

       Skipping cache restore (new runtime signature)

-----> Building dependencies

       Prebuild detected (node_modules already exists)

       Rebuilding any native modules

       

       > bson@0.2.2 install /tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/bson

       > (node-gyp rebuild 2> builderror.log) || (exit 0)

       

       

       > kerberos@0.0.3 install /tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/kerberos

       > (node-gyp rebuild 2> builderror.log) || (exit 0)

       

       

       > dtrace-provider@0.2.8 install /tmp/app/node_modules/ldapjs/node_modules/dtrace-provider

       > node-gyp rebuild

       

       gyp: /tmp/app/.heroku/node/common.gypi not found (cwd: /tmp/app/node_modules/ldapjs/node_modules/dtrace-provider) while reading includes of binding.gyp while trying to load binding.gyp

       gyp ERR! configure error

       gyp ERR! stack Error: `gyp` failed with exit code: 1

       gyp ERR! stack     at ChildProcess.onCpExit (/tmp/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:355:16)

       gyp ERR! stack     at ChildProcess.emit (events.js:110:17)

       gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1078:12)

       gyp ERR! System Linux 3.19.0-28-generic

       gyp ERR! command "node" "/tmp/app/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

       gyp ERR! cwd /tmp/app/node_modules/ldapjs/node_modules/dtrace-provider

       gyp ERR! node -v v0.12.13

       gyp ERR! node-gyp -v v2.0.1

       gyp ERR! not ok

       

       npm ERR! Linux 3.19.0-28-generic

       npm ERR! argv "node" "/tmp/app/.heroku/node/bin/npm" "rebuild" "--nodedir=/tmp/app/.heroku/node"

       npm ERR! node v0.12.13

       npm ERR! npm  v2.11.3

       npm ERR! code ELIFECYCLE

       npm ERR! dtrace-provider@0.2.8 install: `node-gyp rebuild`

       npm ERR! Exit status 1

       npm ERR!

       npm ERR! Failed at the dtrace-provider@0.2.8 install script 'node-gyp rebuild'.

       npm ERR! This is most likely a problem with the dtrace-provider package,

       npm ERR! not with npm itself.

       npm ERR! Tell the author that this fails on your system:

       npm ERR!     node-gyp rebuild

       npm ERR! You can get their info via:

       npm ERR!     npm owner ls dtrace-provider

       npm ERR! There is likely additional logging output above.

       

       npm ERR! Please include the following file with any support request:

       npm ERR!     /tmp/app/npm-debug.log

-----> Build failed

       

       We're sorry this build is failing! You can troubleshoot common issues here:

       https://devcenter.heroku.com/articles/troubleshooting-node-deploys

       

       Some possible problems:

       

       - node_modules checked into source control

       https://docs.npmjs.com/misc/faq#should-i-check-my-node-modules-folder-into-git

       

       Love,

       Heroku
```

**Comment by jvshahid** [comment]
@samdai is the application you are trying to push open source ? it would be very helpful if we can reproduce this issue locally so we can investigate.

**Comment by samdai** [comment]
sorry, this application is not open source. When I deployed this nodejs application to diego using nodejs buildpack version 1.5.8, it works, the following is the log when starting this application, hope it help you to find out some useful clue.

```
Creating container
Successfully created container
Downloading app package...
Downloaded app package (4.8M)
Staging...
-------> Buildpack version 1.5.8
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  ~0.12.7
       engines.npm (package.json):   ~2.11.3
       
       Downloading and installing node 0.12.12...
       Downloaded [file:///tmp/buildpacks/22639bb8535b7aed430e50ca9e4f7f34/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_node_node-0.12.12-linux-x64.tgz]
       Resolving npm version ~2.11.3 via semver.io...
       Downloading and installing npm 2.11.3 (replacing version 2.14.9)...
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Prebuild detected (node_modules already exists)
       Rebuilding any native modules
       
       
       > bson@0.2.2 install /tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/bson
       > (node-gyp rebuild 2> builderror.log) || (exit 0)
       make: Entering directory `/tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/bson/build'
       CXX(target) Release/obj.target/bson/ext/bson.o
       make: Leaving directory `/tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/bson/build'
       
       > kerberos@0.0.3 install /tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/kerberos
       > (node-gyp rebuild 2> builderror.log) || (exit 0)
       
       make: Entering directory `/tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/kerberos/build'
       SOLINK_MODULE(target) Release/obj.target/kerberos.node
       COPY Release/kerberos.node
       make: Leaving directory `/tmp/app/node_modules/mongoskin/node_modules/mongodb/node_modules/kerberos/build'
       
       > dtrace-provider@0.2.8 install /tmp/app/node_modules/ldapjs/node_modules/dtrace-provider
       > node-gyp rebuild
       
       make: Entering directory `/tmp/app/node_modules/ldapjs/node_modules/dtrace-provider/build'
       TOUCH Release/obj.target/DTraceProviderStub.stamp
       make: Leaving directory `/tmp/app/node_modules/ldapjs/node_modules/dtrace-provider/build'
       
       > scrypt@4.0.7 install /tmp/app/node_modules/scrypt
       > node-gyp rebuild
```

**Comment by Dannyzen** [comment]
Hey @samdai, I understand your project is closed source but would there be a possibility you could share your packages.json with us? That might help the team reproduce the issue and diagnose the problem faster.

**Comment by samdai** [comment]
The content of package.json is as below, we include the dependencies node modules in our code, if you want package.json or version of one node module, please let me know, thanks.
```
{ "name" : "AuthServer"
, "description": "OAuth Provider"
, "version": "0.1.0"
, "dependencies": {
    "connect": ""
  , "connect-form": ""
  , "connect-sts": ""
  , "cookie-sessions": ""
  , "formidable": ""
  , "futures" : ""
  , "mongoskin": ""
  , "mustache": ""
  , "nodeunit": ""
  , "pg": ""
  , "pg-large-object": ""
  , "jsrsasign": ""
  , "request": ""
  , "log": ""
  , "oauth2-server": ""
  , "ldapjs": ""
  }
, "engines" : {
    "node" : "~0.12.7",
    "npm" : "~2.11.3"
   }
}
```

**Comment by davidjahn** [comment]
@samdai Hi Sam, we tried to push a sample app with your `package.json` and we cannot reproduce your problem.

1. Is this your actual `package.json` file, or have you removed all the versions for this sample?
1. Can you give us any more information about your environment?
1. Does this issue still happen when you clear your app's node_modules directory with `rm -rf node_modules/` , `cf delete` your application then try to push it again?

Any more information you can give us will be useful, as we cannot reproduce your problem currently.

**Comment by samdai** [comment]
@davidjahn: Thanks your help, the following is my answer of your questions, this issue is a little weird, we also plan to upgrade the nodejs version of this application, this issue might gone after we upgraded nodejs version.
1. This is my actual package.json file. 
2. My application is implemented in nodejs, it's an oauth server, like https://github.com/AF83/auth_server.
3. Yes, this issue still happen when I clear my app's node_modules directory with rm -rf node_modules/ , cf delete my application then try to push it again
```
Staging...
-------> Buildpack version 1.5.11
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  ~0.12.7
       engines.npm (package.json):   ~2.11.3
       
       Downloading and installing node 0.12.13...
       Downloaded [file:///tmp/buildpacks/db690bfa59121d91a378b0db71155aa0/dependencies/https___pivotal-buildpacks.s3.amazonaws.com_concourse-binaries_node_node-0.12.13-linux-x64.tgz]
       Resolving npm version ~2.11.3 via semver.io...
-----> Build failed
       
       We're sorry this build is failing! You can troubleshoot common issues here:
       https://devcenter.heroku.com/articles/troubleshooting-node-deploys
```

**Comment by Dannyzen** [comment]
It looks as though your version of node is not supported by the 1.5.11 buildpack version you're using. 
For a list of supported versions of node for 1.5.11, check out the [releases](https://github.com/cloudfoundry/nodejs-buildpack/releases/tag/v1.5.11) page for that version. There you can find a "packaged binaries" table that highlights what node versions we support.

**Comment by Dannyzen** [comment]
@samdai I stand corrected. As your `packages.json` contains a `~` it should attempt to use the newest version of that version line (0.12.x). Apologies for the false alarm.

**Comment by samdai** [comment]
Have resolved this issue, the solution is  change the npm version of package.json from ~2.11.3 to ~2.15.0 .
Change 
```
, "engines" : {
    "node" : "~0.12.7",
    "npm" : "~2.11.3"
   }
```
into:
```
, "engines" : {
    "node" : "~0.12.7",
    "npm" : "~2.15.0"
   }
```
