### ISSUE TITLE
Yarn with network problem

### ISSUE THREAD

**Issue by SimonCheung1989** [cloudfoundry/nodejs-buildpack#93]
Hi,
  when i use npm to install package, it's all fine, but when i use yarn add package, i can find the error message from yarn-error.log, i had set http_proxy, https_proxy,
```
Trace:
  Error: https://registry.yarnpkg.com/lodash: tunneling socket could not be established, statusCode=403
      at ClientRequest.onConnect (/home/vcap/app/.cloudfoundry/0/yarn/lib/yarn-cli.js:122268:19)
      at ClientRequest.g (events.js:292:16)
      at emitThree (events.js:116:13)
      at ClientRequest.emit (events.js:194:7)
      at Socket.socketOnData (_http_client.js:394:11)
      at emitOne (events.js:96:13)
      at Socket.emit (events.js:188:7)
      at readableAddChunk (_stream_readable.js:176:18)
      at Socket.Readable.push (_stream_readable.js:134:10)
      at TCP.onread (net.js:547:20)
```

**Comment by sclevine** [comment]
Thanks @SimonCheung1989,

We'll investigate and let you know if yarn is misbehaving in this case.

**Comment by sclevine** [comment]
We weren't able to replicate this failure. I'm closing this issue for now, but please let us know if you're still experiencing this issue.
